### ISSUE TITLE
There aren't enough Rick and Morty references in the extension

### ISSUE THREAD

**Issue by lukekrikorian** [ka-extension/ka-extension#7]
I suggest making every element on the page have a css `background` property with a url that points to something Rick and Morty related, which i'll leave up to debate. I would suggest a picture of pickle rick.

**Comment by JettBurns14** [comment]
No

**Comment by lukekrikorian** [comment]
but im PICKEL RICK !!!!!!!!!!!!!!

**Comment by jena0** [comment]
yes but a piclke?

**Comment by lukekrikorian** [comment]
elmt is that you
